"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import Link from "next/link";
import ContractorAvailabilityMap,{AvailableContractor} from "@/components/availability/ContractorAvailabilityMap";
type Service={id:number;name:string}; const API=process.env.NEXT_PUBLIC_API_URL??"http://localhost:8080/api"; const DEFAULT_LOCATION={latitude:20.9971,longitude:75.5621};
function authHeaders(){const token=typeof window!=="undefined"?window.localStorage.getItem("reno_access_token"):null;return token?{Authorization:`Bearer ${token}`}:{}}
async function readApi<T>(response:Response):Promise<T>{const body=await response.json().catch(()=>null);if(response.status===401)throw new Error("Your session has expired. Please sign in again.");if(!response.ok||body?.success===false)throw new Error(body?.message??body?.data?.message??"Request failed");return body?.data??body;}
export default function BookPage(){
 const [services,setServices]=useState<Service[]>([]),[serviceId,setServiceId]=useState(""),[location,setLocation]=useState(DEFAULT_LOCATION),[contractors,setContractors]=useState<AvailableContractor[]>([]),[selected,setSelected]=useState<AvailableContractor|null>(null),[loading,setLoading]=useState(false),[servicesLoading,setServicesLoading]=useState(true),[message,setMessage]=useState(""),[messageType,setMessageType]=useState<"error"|"success"|"">("");
 useEffect(()=>{let active=true;setServicesLoading(true);fetch(`${API}/services`,{headers:authHeaders()}).then(readApi<Service[]>).then(x=>{if(active)setServices(x??[])}).catch(e=>{if(active){setMessage(e instanceof Error?e.message:"Unable to load services.");setMessageType("error")}}).finally(()=>active&&setServicesLoading(false));return()=>{active=false}},[]);
 const findNearby=useCallback(async()=>{if(!serviceId){setMessage("Choose a service first.");setMessageType("error");return}setLoading(true);setMessage("");setMessageType("");try{const p=new URLSearchParams({serviceId,latitude:String(location.latitude),longitude:String(location.longitude),radiusKm:"10",limit:"20"});const x=await readApi<AvailableContractor[]>(await fetch(`${API}/contractors/nearby?${p}`,{headers:authHeaders()}));setContractors((x??[]).map(c=>({...c,name:c.name??`Contractor #${c.contractorId}`})));setSelected(null);if(!(x??[]).length){setMessage("No available contractor was found within 10 km. Try another service or location.");setMessageType("error")}}catch(e){setMessage(e instanceof Error?e.message:"Unable to find contractors.");setMessageType("error")}finally{setLoading(false)}},[serviceId,location]);
 const useLocation=()=>{if(!navigator.geolocation){setMessage("Your browser does not support location services.");setMessageType("error");return}setLoading(true);navigator.geolocation.getCurrentPosition(p=>{setLocation({latitude:p.coords.latitude,longitude:p.coords.longitude});setLoading(false);setMessage("Location updated. Search again to refresh nearby contractors.");setMessageType("success")},()=>{setLoading(false);setMessage("Location permission was not granted. You can still search from the default location.");setMessageType("error")},{enableHighAccuracy:true,timeout:10000,maximumAge:30000})};
 const book=async()=>{if(!selected||!serviceId)return;const token=typeof window!=="undefined"?window.localStorage.getItem("reno_access_token"):null;if(!token){setMessage("Sign in is required before booking.");setMessageType("error");return}setLoading(true);setMessage("");setMessageType("");try{await readApi(await fetch(`${API}/bookings`,{method:"POST",headers:{...authHeaders(),"Content-Type":"application/json"},body:JSON.stringify({contractorId:selected.contractorId,serviceId:Number(serviceId),latitude:location.latitude,longitude:location.longitude,address:"Customer selected map location"})}));setMessage("Booking confirmed. The contractor has been reserved for you.");setMessageType("success");setSelected(null);await findNearby()}catch(e){setMessage(e instanceof Error?e.message:"Booking failed. Please choose another contractor and try again.");setMessageType("error")}finally{setLoading(false)}};
 const onSelect=useCallback((c:AvailableContractor)=>setSelected(c),[]); const sorted=useMemo(()=>[...contractors].sort((a,b)=>a.distanceKm-b.distanceKm),[contractors]);
 return <main className="shell"><header className="topbar"><Link className="brand" href="/">Reno</Link><div className="user-chip">Customer <span>Book a service</span></div></header><section className="hero"><div><p className="eyebrow">Instant service</p><h1>Find a contractor near you</h1><p className="muted">Choose a service and see available contractors nearby.</p></div></section><section className="panel" style={{padding:24,marginBottom:18}}><div className="form-grid"><label>Service<select aria-label="Service" value={serviceId} onChange={e=>setServiceId(e.target.value)} disabled={servicesLoading}><option value="">{servicesLoading?"Loading services…":"Choose a service"}</option>{services.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Location<input aria-label="Current location" value={`${location.latitude.toFixed(4)}, ${location.longitude.toFixed(4)}`} readOnly/></label></div><div className="action-row"><button className="primary" onClick={useLocation} disabled={loading}>Use my location</button><button className="primary" onClick={findNearby} disabled={loading||servicesLoading||!serviceId}>{loading?"Working…":"Find contractors"}</button>{message&&<span className={`notice ${messageType}`} role="status" aria-live="polite">{message}</span>}</div></section><div className="booking-layout"><section className="panel" style={{padding:10}}><ContractorAvailabilityMap contractors={sorted} customerLocation={location} onSelect={onSelect}/></section><section className="panel" style={{padding:20}}><h2>Available nearby</h2><p className="muted" style={{marginBottom:14}}>Sorted by distance. Contractor location is approximate until booking.</p>{!sorted.length?<p className="state">Search for a service to see available contractors.</p>:sorted.map(c=><button className={`contractor-card ${selected?.contractorId===c.contractorId?"selected":""}`} key={c.contractorId} onClick={()=>setSelected(c)} aria-pressed={selected?.contractorId===c.contractorId}><strong>{c.name}</strong><div className="muted">{c.distanceKm.toFixed(1)} km away{c.etaMinutes?` • ${c.etaMinutes} min ETA`:""}</div><div style={{marginTop:6}}>⭐ {(c.rating??4.8).toFixed(1)} · Verified · Score {c.qualityScore??"—"}</div></button>)}{selected&&<div style={{borderTop:"1px solid #eef0f3",paddingTop:16,marginTop:14}}><strong>{selected.name}</strong><p className="muted" style={{margin:"6px 0 12px"}}>{selected.distanceKm.toFixed(1)} km away. Exact contractor location is not exposed before booking.</p><button className="primary" onClick={book} disabled={loading}>{loading?"Booking…":"Book now"}</button></div>}</section></div></main>
}
