"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import ContractorAvailabilityMap, { AvailableContractor } from "@/components/availability/ContractorAvailabilityMap";

type Service={id:number;name:string};
const API=process.env.NEXT_PUBLIC_API_URL??"http://localhost:8080/api";
const DEFAULT_LOCATION={latitude:20.9971,longitude:75.5621};

export default function BookPage(){
 const [services,setServices]=useState<Service[]>([]),[serviceId,setServiceId]=useState(""),[location,setLocation]=useState(DEFAULT_LOCATION),[contractors,setContractors]=useState<AvailableContractor[]>([]),[selected,setSelected]=useState<AvailableContractor|null>(null),[loading,setLoading]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{fetch(`${API}/services`).then(r=>r.ok?r.json():Promise.reject()).then(x=>setServices(x.data??[])).catch(()=>setMessage("Unable to load services."))},[]);
 const findNearby=useCallback(async()=>{if(!serviceId){setMessage("Choose a service first.");return}setLoading(true);setMessage("");try{const p=new URLSearchParams({serviceId,latitude:String(location.latitude),longitude:String(location.longitude),radiusKm:"10",limit:"20"});const r=await fetch(`${API}/contractors/nearby?${p}`);if(!r.ok)throw new Error("Nearby contractor search failed");const x=await r.json();setContractors((x.data??[]).map((c:AvailableContractor)=>({...c,name:c.name??`Contractor #${c.contractorId}`})));setSelected(null)}catch(e){setMessage(e instanceof Error?e.message:"Unable to find contractors.")}finally{setLoading(false)}},[serviceId,location]);
 const book=async()=>{if(!selected||!serviceId)return;setLoading(true);setMessage("");try{const r=await fetch(`${API}/bookings`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({customerId:1,contractorId:selected.contractorId,serviceId:Number(serviceId),latitude:location.latitude,longitude:location.longitude,address:"Customer selected map location"})});if(!r.ok){const body=await r.json().catch(()=>null);throw new Error(body?.message??"Contractor is no longer available. Please choose another.")}setMessage("Booking confirmed. The contractor has been reserved for you.");await findNearby()}catch(e){setMessage(e instanceof Error?e.message:"Booking failed.")}finally{setLoading(false)}};
 const onSelect=useCallback((c:AvailableContractor)=>setSelected(c),[]);
 const sorted=useMemo(()=>[...contractors].sort((a,b)=>a.distanceKm-b.distanceKm),[contractors]);
 return <main className="shell"><header className="topbar"><Link className="brand" href="/">Reno</Link><div className="user-chip">Customer <span>Book a service</span></div></header><section className="hero"><div><p className="eyebrow">Instant service</p><h1>Find a contractor near you</h1><p className="muted">Choose a service and see verified available contractors nearby.</p></div></section><section className="panel" style={{padding:24,marginBottom:18}}><div className="form-grid"><label>Service<select value={serviceId} onChange={e=>setServiceId(e.target.value)}><option value="">Choose a service</option>{services.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Location<input value={`${location.latitude.toFixed(4)}, ${location.longitude.toFixed(4)}`} readOnly/></label></div><div style={{display:"flex",gap:12,marginTop:18,alignItems:"center",flexWrap:"wrap"}}><button className="primary" onClick={()=>navigator.geolocation?.getCurrentPosition(p=>setLocation({latitude:p.coords.latitude,longitude:p.coords.longitude}),()=>setMessage("Location permission was not granted; using the current default location."))}>Use my location</button><button className="primary" onClick={findNearby} disabled={loading}>{loading?"Searching…":"Find contractors"}</button>{message&&<span className="muted" role="status">{message}</span>}</div></section><div style={{display:"grid",gridTemplateColumns:"minmax(0,1.5fr) minmax(320px,.9fr)",gap:18}}><section className="panel" style={{padding:10}}><ContractorAvailabilityMap contractors={sorted} customerLocation={location} onSelect={onSelect}/></section><section className="panel" style={{padding:20}}><h2 style={{marginTop:0}}>Available nearby</h2>{!sorted.length?<p className="state">Search for a service to see available contractors.</p>:sorted.map(c=><button key={c.contractorId} onClick={()=>setSelected(c)} style={{display:"block",width:"100%",textAlign:"left",border:"1px solid #e7e9ee",borderRadius:12,padding:15,marginBottom:10,background:selected?.contractorId===c.contractorId?"#f1f3f6":"#fff",cursor:"pointer"}}><strong>{c.name}</strong><div className="muted">{c.distanceKm.toFixed(1)} km away{c.etaMinutes?` • ${c.etaMinutes} min ETA`:""}</div><div style={{marginTop:6}}>⭐ {(c.rating??4.8).toFixed(1)} · Verified · Score {c.qualityScore??"—"}</div></button>)}{selected&&<div style={{borderTop:"1px solid #eef0f3",paddingTop:16,marginTop:14}}><strong>{selected.name}</strong><p className="muted">{selected.distanceKm.toFixed(1)} km away. Exact contractor location is not exposed before booking.</p><button className="primary" onClick={book} disabled={loading}>{loading?"Booking…":"Book now"}</button></div>}</section></div></main>
}
