"use client";
import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
interface Lead { id:number; name:string; email:string; mobileNumber:string; postalCode:string; description:string; status:string }
interface Service { id:number; name:string; description?:string }
const API = process.env.NEXT_PUBLIC_API_URL ?? "/api/v1";
export default function LeadsPage(){
 const [leads,setLeads]=useState<Lead[]>([]),[q,setQ]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{let active=true;fetch(`${API}/leads`).then(r=>r.ok?r.json():Promise.reject(new Error("Unable to load leads"))).then(x=>{if(active)setLeads(x.data??[])}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
 const filtered=leads.filter(x=>`${x.name} ${x.email} ${x.mobileNumber}`.toLowerCase().includes(q.toLowerCase()));
 return <main className="shell"><header className="topbar"><Link className="brand" href="/">Reno</Link><div className="user-chip">Admin <span>Leads</span></div></header><section className="hero"><div><p className="eyebrow">Customer pipeline</p><h1>Leads</h1><p className="muted">Track every request from first contact to completion.</p></div><Link className="primary" href="/leads/new">Create lead</Link></section><section className="panel"><div className="panel-head"><input aria-label="Search leads" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search by name, email or phone" className="search"/></div>{loading?<p className="state">Loading leads…</p>:error?<p className="state error">{error}. Start the backend and try again.</p>:<div className="table-wrap"><table><thead><tr><th>Name</th><th>Contact</th><th>Location</th><th>Status</th></tr></thead><tbody>{filtered.map(l=><tr key={l.id}><td><strong>{l.name}</strong><br/><small>{l.description}</small></td><td>{l.email}<br/>{l.mobileNumber}</td><td>{l.postalCode}</td><td><span className={`badge ${l.status.toLowerCase()}`}>{l.status}</span></td></tr>)}</tbody></table>{!filtered.length&&<p className="state">No leads match your search.</p>}</div>}</section></main>
}
export function LeadForm(){
 const [services,setServices]=useState<Service[]>([]),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
 useEffect(()=>{let active=true;fetch(`${API}/services`).then(r=>r.ok?r.json():Promise.reject(new Error("Unable to load services"))).then(x=>{if(active)setServices(x.data??[])}).catch(e=>{if(active)setMessage(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");const form=e.currentTarget;const body=Object.fromEntries(new FormData(form));try{const r=await fetch(`${API}/leads`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...body,service:Number(body.service)})});if(!r.ok)throw new Error("Could not create lead");setMessage("Lead created successfully.");form.reset()}catch(err){setMessage(err instanceof Error?err.message:"Something went wrong")}finally{setBusy(false)}}
 return <form onSubmit={submit} className="form-grid"><label>Service<select name="service" required disabled={loading}><option value="">{loading?"Loading services…":"Choose a service"}</option>{services.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Name<input name="name" autoComplete="name" required/></label><label>Email<input name="email" type="email" autoComplete="email" required/></label><label>Mobile number<input name="mobileNumber" autoComplete="tel" required/></label><label>Postal code<input name="postalCode" autoComplete="postal-code" required/></label><label className="full">Description<textarea name="description" rows={5} placeholder="Tell us what work you need…" required/></label><button className="primary" disabled={busy||loading}>{busy?"Creating…":"Create lead"}</button>{message&&<p className="muted" role="status">{message}</p>}</form>
}
